### ISSUE TITLE
Add right click `open link in a new tab` for individual blog posts in `posts` and `series`

### ISSUE THREAD

**Issue by samplelittlered** [AnguHashBlog/angular#30]
**Describe the solution you'd like**
When in the `posts` component, or the `series` component
- upon right click, the user should be able to open the individual blog post in a new tab
- slugs for the blog posts are already in use 

## Open link in a new tab, not open image in a new tab
- must be applied on the blog post card a s a whole

**Comment by jhonacs2** [comment]
@samplelittlered @monacodelisa I was checking the code and well i changed the click of html  <a> and now it works perfectly, we have the option to open a new post in a new tab.
![image](https://github.com/AnguHashBlog/angular/assets/75391330/eeb20a61-caa4-46ed-865f-058b108cd77f)
I tested it and it is working perfectly, what do you think? or is there a scenario that is not being considered?

**Comment by monacodelisa** [comment]
@jhonacs2 yes I think that was it, I assigned it to you, please apply it on the `posts` page and on the `series` page.
And one more tiny thing since you are there - you see how there is a space before the comma on `[post ,post.slug]`, 
please if you can make sure the space is after the comma like this `[post, post.slug]` in both places, thank you for lookin into it :)
